const express = require('express');
const dotenv = require("dotenv");
dotenv.config();
require("./config/dbConnect");
const studentRoute = require("./routes/student.routes");
const companyRoute = require("./routes/company.routes");
const { notFoundHandler, errorHandler } = require('./middlewares/errorHandler');
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use("/company", companyRoute);
app.use("/", studentRoute);
app.use(notFoundHandler);
app.use(errorHandler);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
